### ISSUE TITLE
sagemaker setup

### ISSUE THREAD

**Issue by IaroslavR** [fastai/course-v3#104]
Maybe it will be good to mention about mounting `efs` disk possibility instead of adding 50Gb to every notebook  instance. Can be useful for share datasets etc. between all aws instances.  https://aws.amazon.com/blogs/machine-learning/mount-an-efs-file-system-to-an-amazon-sagemaker-notebook-with-lifecycle-configurations/

**Comment by IaroslavR** [comment]
@kerrieclark831 if we talk in terms of price, sagemaker storage looks [better](https://aws.amazon.com/sagemaker/pricing/) - $0.14 per GB-month, but sagemaker provide closed infrastructure (no real ssh for example) and this future can be useful for shared datasets/models if one need it

**Comment by kerrieclark831** [comment]
@laroslavR - absolutely! I just added EFS pricing for transparency.

**Comment by jph00** [comment]
I haven't found EFS useful for this purpose, because the small file latency is too high.
