### ISSUE TITLE
"learn = ConvLearner(...)" missing in lesson1 notebook

### ISSUE THREAD

**Issue by cwerner** [fastai/course-v3#12]
The notebook lacks this line (or something like this?) and thus does not work out of the box...

`learn = ConvLearner(data, models.resnet34, metrics=error_rate)
`

Might have accidentally been deleted in one of the last commits?

**Comment by shirishr** [comment]
or maybe it is going to be the punch line :-). The 1.0 looks good and docs.fast.ai is very helpful !! I could fill in the missing cells, correct cells where necessary and ran the whole notebook.

**Comment by lesscomfortable** [comment]
The line is there now.

**Comment by tobystic** [comment]
Ah! @fpingham   it seems they took it out again . Luckily I found another learner: 
learn = cnn_learner(data, models.resnet18, metrics=accuracy) 
The two methods seem to take similar parameters and learn.fit works just fine
