### ISSUE TITLE
You shoud add missing string with import fastai

### ISSUE THREAD

**Issue by kuilef** [fastai/course-v3#129]
`from fastai.text import *`
is not enough.

Thou should also add:
`from fastai import *`

**Comment by jph00** [comment]
Where are you seeing this problem?

**Comment by kuilef** [comment]
sorry for the ambiguity: **lesson3-imdb.ipynb**
if only `from fastai.text import *`
then next string 
`torch.cuda.set_device(0)` raise error 
`NameError: name 'torch' is not defined`

with added `from fastai import *` all is working
fastai 1.0.34, google cloud server with ubuntu & cuda

**Comment by jph00** [comment]
Oh thanks for letting us know. We should remove that set_device line actually!
