### ISSUE TITLE
Lesson 3 IMDB example :  KeyError: 'unsup'

### ISSUE THREAD

**Issue by zhangjiekui** [fastai/course-v3#130]
data_clas = (TextList.from_folder(path, vocab=data_lm.vocab)
             #grab all the text files in path
             .split_by_folder(valid='test')
             #split by train and valid folder (that only keeps 'train' and 'test' so no need to filter)
             .label_from_folder(classes=['neg', 'pos'])
             .filter_missing_y()    #the error is the same even comments this line
             #label them all with their folders
             .databunch(bs=bs))

data_clas.save('tmp_clas')

KeyError                                  Traceback (most recent call last)
/usr/anaconda/envs/pytorch10/lib/python3.7/site-packages/fastai/data_block.py in process_one(self, item)
    277     def process_one(self,item):
--> 278         try: return self.c2i[item] if item is not None else None
    279         except:

KeyError: 'unsup'

...
exception: Your validation data contains a label that isn't present in the training set, please fix your data.

**Comment by dinhju** [comment]
had the same issue and „fixed” it by moving the unsup out of the data folder.

**Comment by zhangjiekui** [comment]
yes , bug I think it's a bug.  maybe some filters are needed!

i had tryed "label_from_folder(classes=['neg', 'pos'])"  ---->  "label_from_folder()"  
at least this line runs correctly

**Comment by agarnitin86** [comment]
My train and test set has proper distribution with number of samples in each class much greater than 5 still i am getting same error

**Comment by jph00** [comment]
It sounds like you might have the wrong dataset. Please ask on the forum if you're still stuck.
