### ISSUE TITLE
Google Cloud Platform-->lesson3-imdb.ipynb: Error: "untar_data  is not defined"

### ISSUE THREAD

**Issue by Skepticwala** [fastai/course-v3#135]
Hi !
I am running fast.ai course v3 on GCP(Google Cloud Platform) after following the instruction from here:
[Server setup Google Cloud] (https://course-v3.fast.ai/start_gcp.html).
When I am executing the following line **path = untar_data(URLs.IMDB_SAMPLE)** , I am getting following error:
_NameError: name 'untar_data' is not defined_

**Comment by Skepticwala** [comment]
I resolved it by using **from fastai import ***.
How can I know which module have function definition, if some function is not defined?

**Comment by aayushmnit** [comment]
You can search the documentation https://docs.fast.ai/ with your function. Or in your notebook type "?untar_data" to know the file in which the function is contained.

**Comment by Skepticwala** [comment]
Thanks a lot
