### ISSUE TITLE
 NameError: name 'TextLMDataBunch' is not defined

### ISSUE THREAD

**Issue by SkullFang** [fastai/course-v3#137]
My list of environments is
Package             Version          
------------------- -----------------
backcall            0.1.0            
Bottleneck          1.2.1            
certifi             2018.11.29       
chardet             3.0.4            
cycler              0.10.0           
cymem               2.0.2            
cytoolz             0.9.0.1          
dataclasses         0.6              
decorator           4.3.0            
dill                0.2.8.2          
fastai              1.0.0            
fastprogress        0.1.18           
idna                2.8              
ipython             7.2.0            
ipython-genutils    0.2.0            
jedi                0.13.2           
kiwisolver          1.0.1            
matplotlib          3.0.2            
msgpack             0.5.6            
msgpack-numpy       0.4.3.2          
murmurhash          1.0.1            
numexpr             2.6.9            
numpy               1.15.4           
nvidia-ml-py3       7.352.0          
packaging           18.0             
pandas              0.23.4           
parso               0.3.1            
pexpect             4.6.0            
pickleshare         0.7.5            
Pillow              5.4.1            
pip                 18.1             
plac                0.9.6            
preshed             2.0.1            
prompt-toolkit      2.0.7            
ptyprocess          0.6.0            
Pygments            2.3.1            
pyparsing           2.3.0            
python-dateutil     2.7.5            
pytz                2018.9           
PyYAML              3.13             
regex               2018.1.10        
requests            2.21.0           
scipy               1.2.0            
setuptools          40.6.3           
six                 1.12.0           
spacy               2.0.16           
thinc               6.12.0           
toolz               0.9.0            
torch               1.0.0            
torch-nightly       1.0.0.dev20190104
torchvision         0.2.1            
torchvision-nightly 0.2.1            
tqdm                4.29.0           
traitlets           4.3.2            
typing              3.6.6            
ujson               1.35             
urllib3             1.24.1           
wcwidth             0.1.7            
wheel               0.32.3           
wrapt               1.10.11 

error:
NameError: name 'TextLMDataBunch' is not defined

**Comment by jph00** [comment]
Please use the forums for help.

**Comment by xivan128** [comment]
Have you found a solution? I need one yet
