### ISSUE TITLE
Size mismatch when loading `fit_head` in `lesson3-imdb` 

### ISSUE THREAD

**Issue by Skepticwala** [fastai/course-v3#139]
Hi !
 I am using `Google Cloud Platform` for fastai v3 courses.
I am running '**lesson3-imdb.ipynb**' notebook.
Error of size mismatch when loading **'fit_head'**.
Here is the command
```
learn.load('fit_head');
```
I have executed till the following command
```
learn.recorder.plot(skip_end=15)
```
after that I am trying to load the **fit_head**

**Comment by jph00** [comment]
Please use the forums for help.
