### ISSUE TITLE
lesson2 - defaults.device = torch.device('cpu')

### ISSUE THREAD

**Issue by RomRoc** [fastai/course-v3#145]
Following [lesson2](https://github.com/fastai/course-v3/blob/master/nbs/dl1/lesson2-download.ipynb), I export a model trained in GPU (I don't need to export data):
`learn.export()`

Then I upload export.pkl in my laptop (it doesn't have GPU):
```
defaults.device = torch.device('cpu')
l = load_learner(path=Path('./'))
```
I get:
`RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False.`

Instead everything is ok if I move model to CPU before exporting it:
```
learn.model = learn.model.cpu()
learn.export()
``` 
Then I load export.pkl in my laptop (no need to specify `defaults.device` ):
`l = load_learner(path=Path('./'))`

**Comment by sgugger** [comment]
This should be solved in master now, by using `l = load_learner(path=Path('./'), cpu=True)`.

**Comment by austinmw** [comment]
@sgugger was this change before or after 1.0.46?

**Comment by stas00** [comment]
Before 1.0.46. You can see all the release dates here and compare them to the comment date https://github.com/fastai/fastai/releases

**Comment by austinmw** [comment]
@stas00 Thanks. Printing my version says 1.0.46, but `load_learner` says argument `cpu` doesn't exist.

**Comment by stas00** [comment]
I was just answering your specific question...

If I remember correctly, @sgugger made this sorted out internally, so you won't need to pass the arg, see the latest version here:
https://github.com/fastai/fastai/blob/master/fastai/basic_train.py#L573
that change is there in 1.0.46.

**Comment by austinmw** [comment]
Thanks, I guess my error trying to use cpu is due to something besides missing that parameter.

**Comment by sgugger** [comment]
You don't need to set it in the function now, if you have `defauls.device` set to the CPU, it will be loaded on CPU.

**Comment by laavanya-wln** [comment]
@sgugger I have set the defaults.device to cpu , the model does get loaded on CPU , but i notice that some amount of GPU memory also gets used at the same time. Is this possible?

**Comment by kontrabas380** [comment]
@laavanya-wln, @sgugger, I've got the same issue. Have you solved it?
I'm loading model with load_learner and it loads on CPU, but when i'm making predictions with .predict(), some amout of memory on GPU is taken.

**Comment by kontrabas380** [comment]
@sgugger, please answer - I'm still having this problem
