### ISSUE TITLE
CUDA error: all CUDA-capable devices are busy or unavailable

### ISSUE THREAD

**Issue by makamkkumar** [fastai/course-v3#147]
_**When I run the following command there is an error that is coming. I am unable to resolve as there is no ready made solution**
**Note in Cell 11 I executed this command** 

> data.show_batch(rows=3, figsize=(7,6))

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-66824b983385> in <module>
----> 1 data.show_batch(rows=3, figsize=(7,6))

~/anaconda3/lib/python3.7/site-packages/fastai/basic_data.py in show_batch(self, rows, ds_type, **kwargs)
    157     def show_batch(self, rows:int=5, ds_type:DatasetType=DatasetType.Train, **kwargs)->None:
    158         "Show a batch of data in `ds_type` on a few `rows`."
--> 159         x,y = self.one_batch(ds_type, True, True)
    160         if self.train_ds.x._square_show: rows = rows ** 2
    161         xs = [self.train_ds.x.reconstruct(grab_idx(x, i)) for i in range(rows)]

~/anaconda3/lib/python3.7/site-packages/fastai/basic_data.py in one_batch(self, ds_type, detach, denorm, cpu)
    140         w = self.num_workers
    141         self.num_workers = 0
--> 142         try:     x,y = next(iter(dl))
    143         finally: self.num_workers = w
    144         if detach: x,y = to_detach(x,cpu=cpu),to_detach(y,cpu=cpu)

~/anaconda3/lib/python3.7/site-packages/fastai/basic_data.py in __iter__(self)
     69     def __iter__(self):
     70         "Process and returns items from `DataLoader`."
---> 71         for b in self.dl: yield self.proc_batch(b)
     72 
     73     @classmethod

~/anaconda3/lib/python3.7/site-packages/fastai/basic_dat--------------------------------+----------------------+----------------------a.py in proc_batch(self, b)
     63     def proc_batch(self,b:Tensor)->Tensor:
     64         "Proces batch `b` of `TensorImage`."
---> 65         b = to_device(b, self.device)
     66         for f in listify(self.tfms): b = f(b)
     67         return b

~/anaconda3/lib/python3.7/site-packages/fastai/torch_core.py in to_device(b, device)
    103     "Recursively put `b` on `device`."
    104     device = ifnone(device, defaults.device)
--> 105     if is_listy(b): return [to_device(o, device) for o in b]
    106     return b.to(device)
    107 
data.show_batch(rows=3, figsize=(7,6))
~/anaconda3/lib/python3.7/site-packages/fastai/torch_core.py in <listcomp>(.0)
    103     "Recursively put `b` on `device`."
    104     device = ifnone(device, defaults.device)
--> 105     if is_listy(b): return [to_device(o, device) for o in b]
    106     return b.to(device)
    107 

~/anaconda3/lib/python3.7/site-packages/fastai/torch_core.py in to_device(b, device)
    104     device = ifnone(device, defaults.device)
    105     if is_listy(b): return [to_device(o, device) for o in b]
--> 106     return b.to(device)
    107 
    108 def data_collate(batch:ItemsList)->Tensor:

RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
**My output for nividia-smi is as under**
NVIDIA-SMI 384.130                                                                        Driver Version: 384.130--------------------------------+----------------------+----------------------                   |
|------------------------------------------------------+---------------------------------------+--------------------------------------+
| GPU            Name          Persistence -M  | Bus-Id                        Disp.A | Volatile Uncorr.             ECC |
| Fan              Temp  Perf  Pwr:Usage/Cap|                      Memory-Usage | GPU-Util           Compute M. |
|===============================+======================+======================|
|   0          Quadro P4000                    Off  | 00000000:73:00.0            On |                                        N/A |
| 46%          38C    P8             7W / 105W |                 492MiB /  8105MiB |          0%                   Default |
+------------------------------------------------------+---------------------------------------+-------------------------------------+
                                                                               
+-------------------------------------------------------------------------------------------------------------------------------------+
| Processes:                                                                                                                        GPU Memory |
|  GPU       PID        Type                Process name                                                                    Usage      |
|=============================================================================|
|    0          1637            G               /usr/lib/xorg/Xorg                                                                   217MiB |
|    0           3036           G               compiz                                                                                     25MiB |
|    0           5315          G                ...quest-channel-token=8285522418909966745                     62MiB |
|    0          16078          C               /home/anaconda3/bin/python                                                155MiB |
|    0          18196          G               /home/anaconda3/bin/python                                                  26MiB |

**Comment by jph00** [comment]
Please use the forums for support.
