### ISSUE TITLE
lesson3-camvid.ipynb

### ISSUE THREAD

**Issue by vettukal** [fastai/course-v3#149]
`size = src_size//2`

should be changed to 

`size = (src_size//4).tolist()`

Attaching the screenshot: 
![image](https://user-images.githubusercontent.com/1246832/51653498-80c4d380-1f48-11e9-814b-dccffcf7067b.png)

Related discussion on the forum:
https://forums.fast.ai/t/error-in-lesson-3-camvid-with-colab/35329/9?u=vettukal

**Comment by jph00** [comment]
Thanks for the PR - this seems to be a problem in the fastai lib, so we'll fix it there instead. I'll leave the issue open until that's working.

**Comment by sgugger** [comment]
Fixed now with fastai v1.0.41
