### ISSUE TITLE
Runtime error with pytorch nightly

### ISSUE THREAD

**Issue by roberthoglund** [fastai/course-v3#172]
I followed the installation instructions for AWS EC2 but on my local machine. I installed pytorch using `conda install -c pytorch pytorch-nightly cuda92`. After everything was installed I fired up the first notebook but got a runtime error when running the cell that shows images from a batch: `data.show_batch(rows=3, figsize=(7,6))`: "RuntimeError: B should have at least 2 dimensions, but has 1 dimensions instead"

I fixed it by uninstalling pytorch nightly and just installed the latest release of pytorch instead. I ran into this issue when doing an install on the 26th of January, so it could very well work now. I would suggest changing the installation instructions for AWS EC2 to not use pytorch nightly as that could break functionality.

**Comment by jph00** [comment]
Hopefully fixed by https://github.com/fastai/course-v3/pull/180 . Please reopen if not fixed.
