### ISSUE TITLE
Gradient Notebook Container --  No longer available

### ISSUE THREAD

**Issue by PaulAndreRada** [fastai/course-v3#175]
In the [setup page](https://course.fast.ai/start_gradient.html) for the first deep learning course, the recommended base container in the docs is no longer available, and there are 2 possible fast.ai containers. 

### Recommended in the docs:
Fast.ai 1.0 / PyTorch 1.0 BETA

### Available as of January 27, 2019
Paperspace + Fast.AI 1.0 (V3)
Paperspace + Fast.AI 0.7.x

I'm assuming the 1.0(v3) is the right one, but I wanted to ask before I started another machine.
### What's the correct one?

**Comment by jph00** [comment]
v1.0.
