### ISSUE TITLE
Lesson 2, ImageCleaner(ds, idxs, path) does not display the expected window

### ISSUE THREAD

**Issue by HarshaVardhanMA** [fastai/course-v3#188]
I instead get an output like,
HBox(children=(VBox(children=(Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00d\x00d\x00\x00\xff…
Button(button_style='primary', description='Next Batch', layout=Layout(width='auto'), style=ButtonStyle())

**Comment by Undefined01** [comment]
Lesson2-download (even in newest b55d592c7e609f6e692b755acd5cfa2fd6529254) has called `ImageCleaner` without "path" parameter and it will throw an error about `__init__() missing 1 required positional argument: 'path'`

After specified a save path for it, I saw nothing but the kernel's `busing` symbol. 10min later and there was still nothing.

I was running my code at google colaboratory (with gpu)

**Comment by jph00** [comment]
This doesn't work with colab

**Comment by Carlosedo** [comment]
@jph00 Why not? Could you please give some more context?

**Comment by HarshaVardhanMA** [comment]
I am not using colab. I run it locally on my gpu

**Comment by Brycexxx** [comment]
I am using colab, I also meet the problem, the kernel is always busy, output nothing

**Comment by xxx** [comment]
@jph00 could you please reopen this? I'm having this same issue just using GCE.

**Comment by jph00** [comment]
There's a lot of different issues here, but all appear to be user issues, problems that have been since fixed, or unsupported platform issues. So please start by asking on the forum, and if you can get a reproducible problem on a correctly set up supported platform, feel free to open a new issue with those details.

**Comment by xxx** [comment]
Leaving this here because this is the top search result for this problem.

@jph00 In my case this was resolved simply by changing the URL I access the notebook with -

`http://localhost:8080/notebooks/tutorials/fastai/course-v3/nbs/dl1/lesson2-download-Copy1.ipynb` - Accessing this URL directly in the browser works.

`http://localhost:8080/lab?` (then navigate through the menus to get to the notebook) - This fails. Note this is the default redirect target when you hit the root.

The same kernel is being used in both cases.

**Comment by jph00** [comment]
Ah OK you're using JupyterLab. You need to use Jupyter Notebook, not JupyterLab.

**Comment by sheremetyev** [comment]
@HarshaVardhanMA you may need to run the following command

```
jupyter nbextension enable --py widgetsnbextension
```

https://ipywidgets.readthedocs.io/en/stable/user_install.html

**Comment by icrtiou** [comment]
in my settings using jupyter lab from google cloud instance, 
`jupyter nbextension enable --py widgetsnbextension` won't work too. 

So just use jupyter notebook for widgets.

**Comment by Pibastte** [comment]
It doesn't work in colab for me...
I get this error :
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-48-404739740ce3> in <module>()
----> 1 ImageCleaner(ds, idxs, path)

/usr/local/lib/python3.6/dist-packages/fastai/widgets/image_cleaner.py in __init__(self, dataset, fns_idxs, path, batch_size, duplicates)
    108         self._deleted_fns = []
    109         self._skipped = 0
--> 110         self.render()
    111 
    112     @classmethod

/usr/local/lib/python3.6/dist-packages/fastai/widgets/image_cleaner.py in render(self)
    221         "Re-render Jupyter cell for batch of images."
    222         clear_output()
--> 223         self.write_csv()
    224         if self.empty() and self._skipped>0:
    225             return display(f'No images to show :). {self._skipped} pairs were '

/usr/local/lib/python3.6/dist-packages/fastai/widgets/image_cleaner.py in write_csv(self)
    209     def write_csv(self):
    210         # Get first element's file path so we write CSV to same directory as our data
--> 211         csv_path = self._path/'cleaned.csv'
    212         with open(csv_path, 'w') as f:
    213             csv_writer = csv.writer(f)

TypeError: unsupported operand type(s) for /: 'str' and 'str'`

even though I have imported Path from pathlib

If someone has an idea about how I could fix this I would appreciate it.
Thank you.

**Comment by saifabid** [comment]
> It doesn't work in colab for me...
> I get this error :
> `---------------------------------------------------------------------------
> TypeError Traceback (most recent call last)
> in ()
> ----> 1 ImageCleaner(ds, idxs, path)
> 
> /usr/local/lib/python3.6/dist-packages/fastai/widgets/image_cleaner.py in **init**(self, dataset, fns_idxs, path, batch_size, duplicates)
> 108 self._deleted_fns = []
> 109 self._skipped = 0
> --> 110 self.render()
> 111
> 112 @classmethod
> 
> /usr/local/lib/python3.6/dist-packages/fastai/widgets/image_cleaner.py in render(self)
> 221 "Re-render Jupyter cell for batch of images."
> 222 clear_output()
> --> 223 self.write_csv()
> 224 if self.empty() and self._skipped>0:
> 225 return display(f'No images to show :). {self._skipped} pairs were '
> 
> /usr/local/lib/python3.6/dist-packages/fastai/widgets/image_cleaner.py in write_csv(self)
> 209 def write_csv(self):
> 210 # Get first element's file path so we write CSV to same directory as our data
> --> 211 csv_path = self._path/'cleaned.csv'
> 212 with open(csv_path, 'w') as f:
> 213 csv_writer = csv.writer(f)
> 
> TypeError: unsupported operand type(s) for /: 'str' and 'str'`
> 
> even though I have imported Path from pathlib
> 
> If someone has an idea about how I could fix this I would appreciate it.
> Thank you.

Make sure on the top right of your notebook, you have clicked "trusted" notebook

**Comment by franva** [comment]
> @HarshaVardhanMA you may need to run the following command
> 
> ```
> jupyter nbextension enable --py widgetsnbextension
> ```
> 
> https://ipywidgets.readthedocs.io/en/stable/user_install.html

this works for me, thanks
