### ISSUE TITLE
Lesson Titles along with lesson number for Lessons Panel

### ISSUE THREAD

**Issue by skat00sh** [fastai/course-v3#190]
In course-v3/fastai-video-browser/src/components/LessonsPanel.jsx
Do you think it would be good idea to also give lesson name like it has been done for Notes Panel, 
'Lesson 1 : Image Classification'
instead of  
'Lesson 1'

**Comment by jph00** [comment]
If there's room - feel free to try it out and send in a PR if it looks good :)

**Comment by skat00sh** [comment]
I'm unable to setup the project. Any link/instructions?
