### ISSUE TITLE
Documentation for setting up own server

### ISSUE THREAD

**Issue by mogwai** [fastai/course-v3#215]
I have a computer that has a GPU and I managed to install everything mostly following the [AWS EC2 guide](https://course.fast.ai/start_aws.html#). 

Some people may already have decent rigs and it might be good to have a page to help guide people who want to do this? Perhaps some warnings on what to expect when running models e.g. if you have < 10GB VRAM make your batch sizes smaller. 

Also some suggestions on minimum hardware requirements?

**Comment by jph00** [comment]
Feel free to contribute something - otherwise best to check the forum.
