### ISSUE TITLE
Idea: Make branches with adjustments for different python notebook services

### ISSUE THREAD

**Issue by Machiaweliczny** [fastai/course-v3#219]
I started working with fast.ai course - but to make it through on colab (which I still thing is the easiest to start) I have to do a lot of adjustments.

It would be cool if you created branch `colab` where we could propose pull request to fix these issues.
I think everyone going through the course there will have to do such adjustments so it would be nice if you accepted them upstream and suggested `fastai/course-vs` `colab` branch instead of `master` in https://course.fast.ai/start_colab.html

**Comment by jph00** [comment]
What kinds of adjustments are you finding you need? Perhaps we can try to integrate them in to the notebooks (e.g. some kind of run-time test, or just add some prose)? Otherwise we have to maintain two sets of notebooks, which is a lot of overhead.

**Comment by Machiaweliczny** [comment]
Thanks for reply and great course Jeremy.

I'm having minor struggles with adjusting things. So far I got stuck in lesson 3. 
I thought that persons interested in learning concepts can get demotivated by all those minor technical struggles and would be cool to have  lessons working seamlessly in at least one environment.

https://colab.research.google.com/github/fastai/course-v3/blob/master/nbs/dl1/lesson2-download.ipynb

^ for example this lesson doesn't work for me with google drive. Because .txt is changed to .gdoc and `open()` function crashes. (maybe .txt extension can be somehow preserved? - would be nice to mention this at least in https://course.fast.ai/start_colab.html)

https://colab.research.google.com/github/fastai/course-v3/blob/master/nbs/dl1/lesson3-planet.ipynb

For this lesson I had to modify to:
```
! mkdir -p /root/.kaggle/
! echo '{"username":"username","key":"key"}' > /root/.kaggle/kaggle.json
! chmod 600 /root/.kaggle/kaggle.json
```

After that I'm getting 500 server error not 403 when trying to download without accepting competition rules (can't today because maintenance mode on kaggle.com - so maybe that's why I'm getting 500 or maybe because of settings - shrug)

I will update after I progress more.

> Otherwise we have to maintain two sets of notebooks, which is a lot of overhead

Yeah I probably  underestimated the effort .

Anyway this course is still most accessible from all I tried so good job and thanks.

**Comment by jph00** [comment]
I'm not a Colab user myself, but it would be great if folks like you that are working on that platform could help us make the Colab experience better. :) If you're interested, you're welcome to use this issue to track it, or else you could use the official forum thread (where it will get more attention I'd expect) https://forums.fast.ai/t/platform-colab/28161
