### ISSUE TITLE
Lesson 1 - What's your pet

### ISSUE THREAD

**Issue by cswangchen** [fastai/course-v3#236]
when i run lesson1 in colab,
`data = ImageDataBunch.from_name_re(path_img, fnames, pat, ds_tfms=get_transforms(), size=224, bs=bs).normalize(imagenet_stats)`

when it comes to this line,the colab output following errors.
`AssertionError                            Traceback (most recent call last)
<ipython-input-44-0a22055f1fd5> in <module>()
----> 1 data = ImageDataBunch.from_name_re(path_img, fnames, pat, ds_tfms=get_transforms(), size=224, bs=bs).normalize(imagenet_stats)

/usr/local/lib/python3.6/dist-packages/fastai/vision/data.py in from_name_re(cls, path, fnames, pat, valid_pct, **kwargs)
    155             assert res,f'Failed to find "{pat}" in "{fn}"'
    156             return res.group(1)
--> 157         return cls.from_name_func(path, fnames, _get_label, valid_pct=valid_pct, **kwargs)
    158 
    159     @staticmethod

/usr/local/lib/python3.6/dist-packages/fastai/vision/data.py in from_name_func(cls, path, fnames, label_func, valid_pct, **kwargs)
    143     def from_name_func(cls, path:PathOrStr, fnames:FilePathList, label_func:Callable, valid_pct:float=0.2, **kwargs):
    144         "Create from list of `fnames` in `path` with `label_func`."
--> 145         src = ImageList(fnames, path=path).random_split_by_pct(valid_pct)
    146         return cls.create_from_ll(src.label_from_func(label_func), **kwargs)
    147 

/usr/local/lib/python3.6/dist-packages/fastai/data_block.py in random_split_by_pct(self, valid_pct, seed)
    194         if valid_pct==0.: return self.no_split()
    195         if seed is not None: np.random.seed(seed)
--> 196         rand_idx = np.random.permutation(range_of(self))
    197         cut = int(valid_pct * len(self))
    198         return self.split_by_idx(rand_idx[:cut])

mtrand.pyx in mtrand.RandomState.permutation()

mtrand.pyx in mtrand.RandomState.shuffle()

/usr/local/lib/python3.6/dist-packages/numpy/core/_internal.py in __init__(self, array, ptr)
    294             # get a void pointer to the buffer, which keeps the array alive
    295             self._data = _get_void_ptr(array)
--> 296             assert self._data.value == ptr
    297         else:
    298             # fake a pointer-like object that holds onto the reference

AssertionError: `

**Comment by cswangchen** [comment]
pls help me ,new to pytorch.

**Comment by ichko** [comment]
Did you execute
```
!curl -s https://course.fast.ai/setup/colab | bash
```
As the [getting started with colab guide](https://course.fast.ai/start_colab.html) says. If not try that. The version of the fastai lib might be old.

I just ran the same notebook following the guide and it all went smoothly.

**Comment by nemaminejad** [comment]
I get the same error. First time I ran the notebook with colab, everything was fine, but since then I get this error. I am trying to figure out why!

**Comment by nemaminejad** [comment]
Got the same error and solved it this way.
 instead  of
`!curl -s https://course.fast.ai/setup/colab | bash`
I tried:
```
!pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu92/torch_nightly.html
!pip install fastai
```

**Comment by mvivekc** [comment]
I resolved it by reloading numpy couple of times and upgrading pandas ( was 0.22.0 ) to 0.24.2 ( latest now ).
