### ISSUE TITLE
update the notebooks create_cnn -> cnn_learner

### ISSUE THREAD

**Issue by krishnakalyan3** [fastai/course-v3#245]
If we run the notebooks as it we get the error below

![image](https://user-images.githubusercontent.com/4648995/54072416-74020200-42a0-11e9-9077-b3aaf8d82842.png)

`create_cnn` needs to updated to `cnn_learner`. I can submit a pull request if required.

Ref
https://forums.fast.ai/t/nameerror-name-create-cnn-is-not-defined/40321/7

**Comment by sgugger** [comment]
Forgot to push that update, it's done now!
