### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by adrianovieira** [fastai/course-v3#248]
Hi!
I just got this message:

`RuntimeError: CUDA out of memory. Tried to allocate 32.75 MiB (GPU 0; 4.93 GiB total capacity; 3.85 GiB already allocated; 29.69 MiB free; 332.48 MiB cached)`

It happened when I was trying to run the **Fast.ai lesson1 Pets** https://course.fast.ai/ (cell 31)

What coudl I do to fix it?

My environment:

**Fast.ai version**: 1.0.48
**PyTorch version**: 1.0.1
**cudatookit**: 9.0

**NVidia driver**: Quadro P2000 5GB
**CUDA driver**: 390xx-cuda

**Comment by Jestr117** [comment]
There should be a cell with
bs = 64
# bs = 16
I would suggest uncommenting the 16 line so you don't keep getting this error with 4GB of memory on a 970.

**Comment by sgugger** [comment]
That is the right fix (or even a value lower than 16 if you don't have a lot of GPU RAM).
