### ISSUE TITLE
Lesson 7 human-numbers

### ISSUE THREAD

**Issue by mugnaio** [fastai/course-v3#257]
cell number 17, when it says
x1[:,0]

should be x1[0]

next cell y1[:,0]
should be y1[0]

this is now the correct way to see that y is x shifted by 1

**Comment by jph00** [comment]
If this is reporting a bug, could you please show what you're doing exactly, what error you see (paste the stack trace), and what versions of fastai and pytorch you're using on what platform?

**Comment by mugnaio** [comment]
it is not an error on the library but a mistake on the notebook of the lessons I mean this file
https://github.com/fastai/course-v3/blob/master/nbs/dl1/lesson7-human-numbers.ipynb
on the 17th cell it says 
x1[:,0] and in the next cell y1[:,0] to check theirs content
This is the same code on the video but maybe the library is changed since then because now if you check x1[:,0] and y1[:,0] what you actually see doesn't show what it meant to show (y is the x shifted by 1 position). The right code tho show that now it to check  x1[0] and y1[0]

In fact, few cell later when the notebook shows the same content but with words instead number it correctly (this time) check  v.textify(x1[0]) and v.textify(y1[0])  (not v.textify(x1[:,0] ) and v.textify(y1[:,0]))

sorry for my english, I understand maybe I can't explain this thing right

the point is no bug in the library, to me just the notebook of the lesson needs a small fix

**Comment by jph00** [comment]
I just checked and it's working fine - please check you've got the latest version of fastai, and ask on the forum if you're still having trouble.
