### ISSUE TITLE
SageMaker setup instructinos

### ISSUE THREAD

**Issue by miwojc** [fastai/course-v3#268]
from short DL workshop with SageMaker, one of the cool things they do was to run main notebook on cpu instance (for data import, data wrangling, etc) so it's cheaper. Then from the main notebook, they create a separate instance or instances with gpu and pass data there and once training is done they get the results back to the main notebook and training instance is automatically stopped to avoid cost, same for deployment.
The main notebook calls and creates training and deployment instances. I don't see this approach in the SageMaker setup for fastai. I just wonder if that would make sense to implement that?

**Comment by jph00** [comment]
It's extra complexity I'd rather leave out of the main guide - but could be added as a note towards the bottom if anyone feels like contributing that. Thanks for the suggestion.
