### ISSUE TITLE
Update instructions in docs/update_crestle.md don't properly update fastai library

### ISSUE THREAD

**Issue by ratelle** [fastai/course-v3#269]
The instructions in docs/update_crestle.md mention `git pull` on the course material but the update instructions don't properly use the pytorch channel. This prevents installing a version over 1.0.38.

They should read

```
conda update conda
conda install -c pytorch -c fastai fastai
```

This issue might be present on update instructions for other services. I have not confirmed.

**Comment by jph00** [comment]
Thanks! A PR would be much appreciated, if you have a moment. :)

**Comment by ratelle** [comment]
Hi, crestle.ai are supposed update their fastai instructions soon to fix some issues that users have been facing. I'll see if they do this week and I'll open a PR if they don't

**Comment by jph00** [comment]
Did they fix it?
