### ISSUE TITLE
Install with Mac instructions for Google Cloud  start_gcp.md

### ISSUE THREAD

**Issue by discdiver** [fastai/course-v3#27]
Thank you for the install guides! 

for _start_gcp.md_

In Step2: Install Google CLI

The [page](https://cloud.google.com/sdk/docs/quickstart-macos) I was referred to in the guide got me lost in python version land and I wasn't able to install from it.

To get to work on a Mac I found it easiest to follow Google's instructions at [https://cloud.google.com/sdk/docs/downloads-interactive](https://cloud.google.com/sdk/docs/downloads-interactive). 

```
      curl https://sdk.cloud.google.com | bash
      exec -l $SHELL
```

![screen shot 2018-10-23 at 8 47 54 am](https://user-images.githubusercontent.com/7703961/47362334-2ba3c800-d6a2-11e8-86d6-a4265c605500.png)

Could I submit a pull request to change?

**Comment by lesscomfortable** [comment]
Yes, please submit a PR.
