### ISSUE TITLE
Workflow to contribute to the notebooks

### ISSUE THREAD

**Issue by ajthinking** [fastai/course-v3#279]
I wanted to add a line in lesson5-sgd-mnist and did a PR. But the azure CI thing showed errors…
![image](https://user-images.githubusercontent.com/3457668/56113943-f82b6180-5f91-11e9-89b0-50f93681d91b.png)
![image](https://user-images.githubusercontent.com/3457668/56113951-fd88ac00-5f91-11e9-9d65-4470b78e1ca5.png)
Investigating that I found my small one line change had also introduced some weird metadata changes. Im suspecting this is why I get the error?
![image](https://user-images.githubusercontent.com/3457668/56113969-0bd6c800-5f92-11e9-9514-9dee9b32e93b.png)

### What I did
* forked fastai/course-v3
* cloned to my GCP instance: ~/projects/course-v3-improvements (I like to * keep the ~/tutorials folder strict read only)
* open the notebook and add my line, then press the save button
* commit, push and make PR

[The actual PR](https://github.com/fastai/course-v3/pull/275) (I closed it until I figure this out):

Where did I go wrong here? What is your workflow for doing a PR? Do I need to set up my own Azure pipeline so I can actually test it before submitting?

**Comment by jph00** [comment]
Here's the steps you need: https://docs.fast.ai/dev/develop.html

Many thanks!
