### ISSUE TITLE
Unable to deploy Azure DSVM

### ISSUE THREAD

**Issue by nikulk** [fastai/course-v3#293]
![image](https://user-images.githubusercontent.com/14416783/57978039-85127200-79b9-11e9-9b51-ee374aeec544.png)

Getting this issue when following the steps for Linux DSVM here: 
https://course.fast.ai/start_azure.html#using-dsvm-for-fastai

Does the image version need to be updated? or some other fix? known issue?

Thanks,
Neil

**Comment by OzzieFZI** [comment]
I get the same error.

Disk: "Standard_D4s_v3 (4 vCPU, 16 GB)"

The pre-emptable version template under [https://course.fast.ai/start_azure.html#lowering-your-cloud-compute-cost](url) only created a Virtual machine scale sets resource, which I am not sure how to use.

**Comment by jph00** [comment]
We don't maintain the Azure docs, so could you please ask on the forum?
