### ISSUE TITLE
Example project to deploy to AWS failed to load container: config.v2.json no such file or directory

### ISSUE THREAD

**Issue by lmiguelmh** [fastai/course-v3#297]
First, I want to say thanks for those who make this excellent course!
I was following this guide for [deploying a model on AWS Lambda](https://course.fast.ai/deployment_aws_lambda.html) until the part where I had to test the lambda function locally for what I used the next command:

```
sam local invoke PyTorchFunction -n env.json -e event.json
```

After some time the command fails with the message: 
```
...
2019-05-21 17:39:23 Invoking app.lambda_handler (python3.6)
2019-05-21 17:39:23 arn:aws:lambda:us-east-1:934676248949:layer:pytorchv1-py36:2 is already cached. Skipping download
...
2019-05-21 17:39:23 Mounting /.../aws-lambda/pytorch as /var/task:ro,delegated inside runtime container
2019-05-21 17:39:53 Function 'PyTorchFunction' timed out after 30 seconds
```

Enabling [verbose logging](https://gist.github.com/lmiguelmh/2aaba4f0ab7fdc40692291a81103f032#file-sam-local-invoke-log) I realize it was a problem with the Docker container. So, I decide to dig a little more and found the next messages on [Docker logs](https://gist.github.com/lmiguelmh/acc75d5f0db1db3903083e384103634a#file-docker-logs-for-sam-local-invoke):

```
... level=error msg="Failed to load container 67ab2499b983f83a29294995013775f0a3810e53f66a6504c63411db4cacdbb6: open /var/lib/docker/containers/67ab2499b983f83a29294995013775f0a3810e53f66a6504c63411db4cacdbb6/config.v2.json: no such file or directory"
```

The message is `Failed to load container config.v2.json: no such file or directory` and I think as the [SAM example project](https://github.com/fastai/course-v3/raw/master/docs/production/aws-lambda.zip) was updated recently  https://github.com/fastai/course-v3/pull/290 (only 4 days ago) ...

PD: I tested the application on Windows 10 and Linux Ubuntu 18.04 with the same result.

**Comment by jph00** [comment]
Many thanks! The lambda docs and toolkit isn't maintained by us - so could you please either add this info to the forum, or else provide a PR that fixes the issue?
