### ISSUE TITLE
lr_find gives different results every time I run it on same data

### ISSUE THREAD

**Issue by AndeYashwanth** [fastai/course-v3#301]
I am facing an issue when I try lr_find and plot it, it gives different plot every time run it.
I am currently running it on google colab with pet images. I ran the code till creating a databunch and started experimenting with the learner.

`learn = cnn_learner(data, models.resnet34, metrics=error_rate)`
`learn.fit_one_cycle(1)`
`learn.lr_find()`
`learn.recorder.plot()`

Every time I run the above 4 lines I get a different graph. Some graphs look totally different.

I thought that training works differently every time I run it. So I only executed the first 2 lines only once and just ran lr_find() and plot() multiple times.

Still I am getting different plots.

**Comment by kakods** [comment]
Are you splitting the data into train and valid using random split?

**Comment by jph00** [comment]
Please use the forums.
