### ISSUE TITLE
from fastai.vision import * raise error,no module found

### ISSUE THREAD

**Issue by thisisreallife** [fastai/course-v3#305]
## Probelm:
I learned fastai deeplearning courseV3. I came across a problem like this:
```
from fastai.vision import *
from fastai.metrics import error_rate
```
Output:
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-30-283c0d40bede> in <module>
----> 1 from fastai.vision import *
      2 from fastai.metrics import error_rate

ModuleNotFoundError: No module named 'fastai.vision'
```
What is the problem?
**I almost try every version combination of torch,torchvision and fastai, things still goes wrong...**
**I think the instructor of deep learning course did not give us the specific version of each package to install.** If I have a setup.txt storing each version of packages this course needed, I can install packages in a new environment automatically!

## My device or software versions:
OS = win10
Python = 3.6
torch = 1.1.0
torchvision = 0.2.2
fastai=1.0.52

I will very appreciate if someone can help me !

**Comment by ah3243** [comment]
likely you have but have you made sure you've selected the correct kernel if you're running it in jupyter?

**Comment by jph00** [comment]
Please use the forums.
