### ISSUE TITLE
lesson2-download.ipynb cannot be viewed

### ISSUE THREAD

**Issue by jseow-c** [fastai/course-v3#325]
Hi!

Wanted to view the code in lesson2-download.ipynb under dl1 but couldn't manage to do it. Is there some changes made that cause it to be unviewable? I'm getting NotJSONError in jupyter notebook. 
In GitHub, it is in infinitely loading.

**Comment by yuanzhiroc** [comment]
The 643 line is missing the comma, and then it's not a json format, the comma on the machine is ok, I don't know why

**Comment by yuanzhiroc** [comment]
Locate the missing comma by looking up plot()

**Comment by yuanzhiroc** [comment]
You can view it, but there are other error message
Notebook JSON is invalid: 'traceback' is a required                     property

    Failed validating 'required' in error:

    On instance['cells'][21]['outputs'][0]:
    {'ename': 'KeyboardInterrupt', 'evalue': '', 'output_type': 'error'}

**Comment by AmgadSalama** [comment]
Same here!

![image](https://user-images.githubusercontent.com/38018859/60181554-bdac3380-9822-11e9-828c-572c75ad5f86.png)

**Comment by twgonzalez** [comment]
Notebook won't load on Salamander either after pulling from GIT.

**Comment by sgugger** [comment]
Solved by #331 normally
