### ISSUE TITLE
not importing fastai causes error "unknown function untar_data"

### ISSUE THREAD

**Issue by Naveenkhasyap** [fastai/course-v3#343]
In notebook lesson1-pets we need to import fastai library 
> from fastai import * 

as the tutorial video it is present but not in notebook
so it won't throw error saying unknown function untar_data.
this looks like #184 issue but not fixed as solution provided was not taken.

**Comment by sgugger** [comment]
You should update your version of fastai if you have an error as this import isn't necessary anymore.
