### ISSUE TITLE
Dataset download fails when following Kaggle server setup documentation

### ISSUE THREAD

**Issue by jonbenfri** [fastai/course-v3#347]
Problem:
Unable to download dataset from Lesson 1 - Pets notebook. Link here:
https://www.kaggle.com/hortonhearsafoo/fast-ai-v3-lesson-1

Cause:
Phone verification is required to enable internet access.

Solution:
Edit instructions `docs/start_kaggle.md` to add phone verification.

See:
https://course.fast.ai/start_kaggle.html

**Comment by jph00** [comment]
Thanks - done.
