### ISSUE TITLE
Crestle pricing changed

### ISSUE THREAD

**Issue by blazejdolicki** [fastai/course-v3#367]
Crestle GPU type changed. It is no longer Tesla K80 as described [here](https://course.fast.ai/start_crestle.html). As mentioned [in the FAQ](https://www.crestle.ai/), now they switched to NVIDIA Tesla P4 and accordingly the pricing changed to 2.40 $/h (which btw seems to me too expensive for a beginner).

**Comment by jph00** [comment]
Thanks for raising this! Any chance you might be able to provide a PR fixing it?

**Comment by APramov** [comment]
Hi all,

piggybacking on this topic, I am not sure if crestle would continue to support individual projects, but rather shifts its focus on offering solutions only for companies. At least this is how I understand it:

[Link to blogpost](https://doc.ai/blog/crestleai-transition-enterprise-model/)

In particular "From now through the end of August you will continue to have access to your instances with support. During this time, make sure to download your data, models and complete your current work. As of August 31, 2019 the service and your data will no longer be accessible on the platform."

Do you also understand it as I do?  I was planning to actually use crestle.ai and I had started a test project...

**Comment by jph00** [comment]
Thanks I've removed Crestle from our docs now.
