### ISSUE TITLE
Questionable logic in __call__ method of runner class?

### ISSUE THREAD

**Issue by fg91** [fastai/course-v3#370]
@jph00 @sgugger 

Please see `__call__` method of `Runner` class in notebook 05b_early_stopping.ipynb:

```python
class Runner():
    ...
    def __call__(self, cb_name):
        res = False
        for cb in sorted(self.cbs, key=lambda x: x._order): res = cb(cb_name) and res
        return res
```

Regardless of whether `cb(cb_name)` returns `True` or `False` `res` **will always equal `False`**. Is this intentional?

Shouldn't we return `True` if one of the callbacks returns `True` because it *intends to stop training*? If that was the intention we should change `res = cb(cb_name) and res` to `res = cb(cb_name) or res`

**Comment by jph00** [comment]
Yes that's correct. Would you be interested in doing a PR with that change? (BTW we refactor the class in a later notebook which is why this hasn't really been an issue in practice - but it would be best for it to be correct!)

**Comment by fg91** [comment]
I created the PR. Truly love the new course by the way!!

**Comment by gnoparus** [comment]
I found the same bug in code so I opened PR  2 days ago. 

https://github.com/fastai/course-v3/pull/418

The master code  haven't changed since last 3 month (Jul 12). Have you submitted PR already? I couldn't find any opened PR related to this issue.

Sorry that I didn't see this issue before. I just found it today.

**Comment by gnoparus** [comment]
I found your PR https://github.com/fastai/course-v3/pull/372

Closed duplicated PR already.
