### ISSUE TITLE
mark suggested lr

### ISSUE THREAD

**Issue by vainaijr** [fastai/course-v3#371]
is it possible to mark a suggested lr, after doing learn.recorder.plot().
like an arrow pointing towards lr which has high probability to work well.

**Comment by deepak-deepklarity** [comment]
@vainaijr You can use learn.recorder.plot(suggestion=True) to get the recommended lr. Please check this link for more details: https://docs.fast.ai/callbacks.lr_finder.html#Suggested-LR 

Also https://forums.fast.ai/ is a better place to ask such questions.
