### ISSUE TITLE
RandomResizedCrop is guaranteed to fail with TypeError when it falls back to a central crop

### ISSUE THREAD

**Issue by dcato98** [fastai/course-v3#384]
In dl2/exp/nb_10.py get_corners, RandomResizedCrop inherits self.crop_size=None from it's parent, GeneralCrop. After 10 failed attempts to randomly generate an appropriate crop, this line will cause a TypeError: 'NoneType' object is not subscriptable.

line 88: left,top = randint(0,w-self.crop_size[0]),randint(0,h-self.crop_size[1])

As for how often this occurs, I successfully ran ~150 epochs on Imagenette before encountering this error.

**Comment by sgugger** [comment]
The code was wrong indeed. I fixed it with the one we developed for v2. Thanks for raisins the issue!
