### ISSUE TITLE
In 09b_learner.ipynb, self('begin_epoch') runs 2 times

### ISSUE THREAD

**Issue by zhangjiekui** [fastai/course-v3#385]
https://github.com/fastai/course-v3/blob/master/nbs/dl2/09b_learner.ipynb

**Comment by zhangjiekui** [comment]
![bug](https://user-images.githubusercontent.com/33198334/63664381-dd4ae280-c7f8-11e9-84f7-831a45603ef8.png)

would it should be like this?

                #self.do_begin_epoch(epoch)
                #if not self('begin_epoch'): self.all_batches()
                if not self.do_begin_epoch(epoch)：self.all_batches()

**Comment by philtrade** [comment]
See [PR 423 ](https://github.com/fastai/course-v3/pull/423).
