### ISSUE TITLE
LSUV works better if we first fix the weight, then the bias!

### ISSUE THREAD

**Issue by fg91** [fastai/course-v3#395]
Interesting observation:

If in the `lsuv_module` *we first adjust the bias, then the weight*, I get the following results for the means and stds of the activations in the conv layers:

```
(0.037135832011699677, 0.9999998807907104)
(0.12191465497016907, 0.9999998807907104)
(0.17217668890953064, 1.0000001192092896)
(0.15430429577827454, 0.9999999403953552)
(0.2998145818710327, 1.0000001192092896)
```

When adjusting the *weights first and then the biases*:

```
(1.7181950084932396e-08, 1.0)
(9.123160005231057e-09, 0.9999999403953552)
(-2.302112989127636e-08, 0.9999998807907104)
(3.317836672067642e-08, 1.0)
(5.587935447692871e-09, 1.0)
```

**Comment by jph00** [comment]
Thanks for the tip! Would you be interested in doing a PR to fix this in the notebook and rerun it?
