### ISSUE TITLE
AWS EC2 doc update

### ISSUE THREAD

**Issue by Michalos88** [fastai/course-v3#399]
Hi, 

I've recently gone through the setup guide of the EC2, and realized a couple of things:

1. Deep Learning AMI (Ubuntu) Version 16.0 is no longer recommend by AWS, so the doc should be updated to Version 24.1 
2. If you run on DLAMI 24.1:
``` bash
conda install -c pytorch -c fastai fastai pytorch torchvision cuda92
```
this will break the environment and should be updated to:
``` bash
conda install -c pytorch -c fastai fastai
```
3. Default storage of a EC2 is not enough for lecture 1 images, so there should be a step about adding larger storage. [(more here)](https://forums.fast.ai/t/disk-full-error-on-ec2/36613)

Is anyone working on it, or is going to be updated with the new release?
If not, happy to prepare a PR. 

Thanks,

**Comment by jph00** [comment]
I think most of those things are fixed now - but if any are missing, a PR would be welcome!
