### ISSUE TITLE
dl1/lesson3-camvid-tiramisu unused, size parameter

### ISSUE THREAD

**Issue by mbant** [fastai/course-v3#419]
In the [lesson3-camvid-tiramisu notebook](https://github.com/fastai/course-v3/blob/master/nbs/dl1/lesson3-camvid-tiramisu.ipynb), 11-th cell just below the "Datasets" section, `size = src_size//2` is defined as it was done for the orginal CamVid notebook, but (I suspect because the size of the modified CamVid dataset is already quite smaller than the original one) the `size` parameter is then not passed to the `transform` function in cell 13.

So it's a minor issue but very quick to fix (just remove the definition in cell 11).
Alternatively we can use the parameter and resize the images, but the notebook would have to be re-run to get the correct output for the learner.

I can open a PR if  somebody tells me which solution is preferable...

**Comment by jph00** [comment]
A quick fix would be just fine - thanks! :)
