### ISSUE TITLE
allow any corrections to the video transcript files?

### ISSUE THREAD

**Issue by davecampbell** [fastai/course-v3#427]
it appears the video transcript files used in the captions on the Video Browser are a first-pass automated transcription, maybe from YouTube?

i've just started viewing them (after getting my GCP environment setup) and was wondering if you'd allow some corrections to be made to them - mostly just where the automated speech-to-text just totally missed something, or adding some proper punctuation, etc.

i've always been a pay-it-forward type, so would be willing to spend a little time as i'm going along to make occasional adjustments to the .json files as i'm watching the videos.  i'm pretty sure future viewers would benefit from this - especially if they are used for search.

i'm not an expert, but i could probably figure out how to do a PR with any changes.

any feedack?  thanks.

**Comment by jph00** [comment]
That would be great! We just grab them from the youtube captions, so you can update them directly in youtube. Thanks for the offer!

**Comment by davecampbell** [comment]
wow, ok, i just finished revising the captions for the week 2 lecture.  it literally took me maybe 6 hours in many 20 minute chunks.  i have to review the value of that endeavor, but i must say that i am REALLY familiar with the content now (which isn't a bad thing).  i'm very impressed with the auto-captioning feature, that it is able to transcribe to the degree that it can.  lots of super-interesting ML at work there (audio waveform image classification in some cases), so plenty of food-for-thought.  i hope these new transcripts will make their way into the distributed tanscript text files, not sure if i should do that piece as well.  i probably can't justify the time to revise any other lectures, at the expense of actually progressing forward,, but i'd be glad to go over the steps for anyone else that is similarly motivated.

**Comment by jph00** [comment]
Amazing! Thanks so much Dave. I've replaced the searchable transcript with this and also published the captions on youtube.
