### ISSUE TITLE
lesson2-camvid.ipynb experiences cuda runtime error (59)

### ISSUE THREAD

**Issue by shirishr** [fastai/course-v3#46]
At 

lr_find(learn)

cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch-nightly_1540500315858/work/aten/src/THC/generic/THCTensorCopy.cpp:20

Such an error does not occur for other notebooks like examples/vision.ipynb

Leads me to believe it is not pytorch-nightly issue

**Comment by shirishr** [comment]
I did a fresh pull of github repo. Updated the lesson2-camvid.ipynb. Replaced my dataset (which came from camvid project site) with dataset from files.fast.ai. I deleted the ipynb_checkpoints and ran the notebook.

I still get cuda error that says:

**RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch-nightly_1540723082246/work/aten/src/THC/generic/THCTensorCopy.cpp:20**

Is there some clean up required to be done once such error occurs. Kernel Restart takes a fair amount of time which suggests that there is some cuda dump taking place. If so maybe the dump needs to be cleaned. It's way over my head ;o)

**Comment by shirishr** [comment]
interesting. are you also experiencing the same issue?

**Comment by stas00** [comment]
No, it works fine for me. I was just trying to help find the cause. I wasn't sure whether you have already looked at some existing discussions around the same error.

I'm yet to run into it myself...

Reading some threads it appears that the problem is either some issue with the labels in the application code or a corrupt cache of the model, but neither seem to apply here. 

Have you tried the latest incarnation? it has now moved to `nbs/dl1/lesson3-camvid.ipynb`

**Comment by shirishr** [comment]
I am working with that version (nbs/dl1/lesson3-camvid.ipynb).
I wonder if codes should be [0,1,2,3,4,5..] instead of [Animal, Archway, Bicyclist...]
Somewhere in the threads people have said that their classes were [1,2,3] which caused the error. The classes should have been [0,1,2] 
By the same logic ... you get my drift.
**Should I close the issue since it works for you?** 
Only diff I can think of is I am on cuda90 not cuda92

**Comment by jph00** [comment]
We're not up to that lesson yet - still working on it. If you have problems after next week please let us know on the forum.

**Comment by shirishr** [comment]
Sure... just a sidebar question.
Why does the code create a models folder and save a tmp.pth file in it?
