### ISSUE TITLE
download-images.ipynb calls 'models' directory before it is created

### ISSUE THREAD

**Issue by andrewreece** [fastai/course-v3#47]
A recent update to [download-images](https://github.com/fastai/course-v3/blob/master/nbs/dl1/download_images.ipynb) includes the line:  
```(path/'models').ls() ```

This is in the second block under **View Data**.  But the `models` directory isn't created until `ConvLearner` is instantiated in the **Train Model** section, which happens after **View Data**.  As it is, calling `ls()` on `models/` throws an error.

**Comment by lesscomfortable** [comment]
Not there anymore.
