### ISSUE TITLE
Can not download pet dataset in lesson1

### ISSUE THREAD

**Issue by Utsav13** [fastai/course-v3#512]
Hey, when I am executing this command in my Jupyter notebook, the download stucks there, means no dataset is downloading using that...
Lesson1:- command
``path = untar_data(URLs.PETS); path``

![Annotation 2020-04-30 170157](https://user-images.githubusercontent.com/35102877/80705658-6c389900-8b04-11ea-85de-db8ab398db4f.png)

can You guide me what is an issue with this ????

**Comment by CaseGuide** [comment]
I tried this today using a SageMaker notebook and had no issues downloading it.

**Comment by Utsav13** [comment]
when am I run using with colab notebook, it works fine. but when I am run in my PC, using this link that is not downloaded, I have windows10 os in my PC, I am run it with jupyter notebook.

**Comment by Utsav13** [comment]
I can not find an original issue but right now I am solving it using manual operations, using wget and tar.
Thanks for ur support.
