### ISSUE TITLE
In lesson2-download, category is not printed

### ISSUE THREAD

**Issue by andresesfm** [fastai/course-v3#531]
Instead what gets printed is: 
Category tensor(0)
Expected: it should print the category such as:
Teddy
 This has been addressed here:
https://github.com/fastai/course-v3/pull/530

**Comment by Chinmay4400** [comment]
The predict function returns 3 objects- prediction class, prediction id and output tensor.
You can get the class name by printing the prediction class.
`
pred_class,pred_idx,outputs = learn.predict(img)
print(pred_class)
`
