### ISSUE TITLE
Google Colab Install error

### ISSUE THREAD

**Issue by myFree** [fastai/course-v3#561]
Hi all; thanks for so much great content.

I'm probably double thumbing this; after updating to use GPU and trying to run the first code block from https://github.com/fastai/course-v3/blob/7dfe63de54daf2210f5b23f237e70ee246be5d0c/docs/google_colab_tutorial.md I'm getting

```
ERROR: Could not find a version that satisfies the requirement torch_nightly (from versions: none)
ERROR: No matching distribution found for torch_nightly
```

Running this bit; I see

```
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
cuda_output[0] if exists('/dev/nvidia0') else 'cpu
```

`cu101`

And I notice on https://download.pytorch.org/whl/nightly/cu101/torch_nightly.html there seem to only be release versions in there `torch-1.7.0....`

But; maybe it relates to the version of pip installed in colab?
https://github.com/pytorch/pytorch/issues/22738

Dropping nightly from the install works; but perhaps nightly is needed by fast.ai?
`!pip install torch -f https://download.pytorch.org/whl/nightly/{accelerator}/torch_nightly.html` I see

`Requirement already satisfied: torch in /usr/local/lib/python3.6/dist-packages (1.6.0+cu101)`

Pip version is
`pip 19.3.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)`

Here is the colab doc
https://colab.research.google.com/drive/16Mdiwylj7wy3o293sF036rByndB3KOsH?usp=sharing

**Comment by myFree** [comment]
Working through https://nbviewer.jupyter.org/github/fastai/course-v3/blob/master/nbs/dl1/lesson3-camvid.ipynb with 1.6 has gone fine up until `learn.show_results` - so I think that means its gone pretty well

What features are only available in nightly?

**Comment by jph00** [comment]
Nightly isn't needed any more - will fix.
