### ISSUE TITLE
seems like the code is inconsistent with latest fastai

### ISSUE THREAD

**Issue by chanansh** [fastai/course-v3#582]
The 1st notebook seems to be inconsistent with the latest fast ai package.
For example: 

```
>>> help(untar_data)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-d1500a12b24c> in <module>
----> 1 help(untar_data)

NameError: name 'untar_data' is not defined

````

This is because namespace of many functions have moved around.

I guess fastbook repo is better. 

@jph00 would be possible to clean this old repo? 
Or at least state which version of fastai do these notebooks work with.

**Comment by jph00** [comment]
Thanks, I've updated the README.
