### ISSUE TITLE
lesson1-pets.ipynb now gives 'expecting number but found string'

### ISSUE THREAD

**Issue by drscotthawley** [fastai/course-v3#64]
Lesson 1 worked fine for me last week, when the state of the file was commit 7346e8712ee03ae413358b9e722dc505306343ac  "Merge pull request #14 from miwojc/correct-regex-link" .

Now, if one grabs a completely fresh clone of the entire course-v3 repo, then the Lesson 1 notebook will produce the error (in Jupyter): 

> "Notebook failed to load
> The error was: [sprintf] expecting number but found string
> See the error console for details."

(and the error console just directs you to a line 3004 in notebook.js which says the same thing). 

Going down through the history of commits for this file, I find that versions *prior* to [commit ceaca31cab5e2909ac102718216f271cf6203688 - "nbs are now stripped out (outputs preserved)"](https://github.com/fastai/course-v3/commit/ceaca31cab5e2909ac102718216f271cf6203688#diff-b18e116269b7ec2cb36c1b8912f90860)   by @stas00  do not produce this error, but from that commit onward (and including it), all of the versions of lesson1-pets.ipynb produce that same error -- including the most recent commit 8ff043fb34031e7cdb7943f29c94e66862b2be6f - "camvid".

**Comment by stas00** [comment]
perhaps you have a merge conflict?
https://docs-dev.fast.ai/troubleshoot#installation-updates

**Comment by drscotthawley** [comment]
There is no merge.  I grab "a completely fresh clone of the entire course-v3 repo."  Deleting the prior directory before doing so. 
Or instead of git-cloning the entire repo, one can simply get the file itself via "curl -LO https://github.com/fastai/course-v3/raw/master/nbs/dl1/lesson1-pets.ipynb"   It makes no difference. The same error persists.
Updating fastai (with conda) has no effect.  Uninstalling both fastai and jupyter and re-installing (via conda) also have no effect.

Are you using a more recent version of Jupyter than is in the conda distribution?   Perhaps we need to build Jupyter from source?
I notice that 8 days ago there was a similar error and talk of a fix:  https://github.com/jupyter/notebook/issues/4065
but in the conda distro the file seems to be 28 days old: https://anaconda.org/anaconda/jupyter

**Comment by stas00** [comment]
Thank you for clarifying that it's not a merge issue.

```
Server Information:
You are using Jupyter notebook.

The version of the notebook server is: 5.7.0
The server is running on this version of Python:
Python 3.6.6 |Anaconda custom (64-bit)| (default, Oct  9 2018, 12:34:16) 
[GCC 7.3.0]

Current Kernel Information:
Python 3.6.6 |Anaconda custom (64-bit)| (default, Oct  9 2018, 12:34:16) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.
```

which is yours?

**Comment by stas00** [comment]
does it change if you do:
`perl -pi -e 's|execution_count": null|execution_count": 1|g' nbs/dl1/*ipynb`
it will change 'null' to a number.

**Comment by drscotthawley** [comment]
@stas00 That solves the problem on my end.  The notebook now loads properly with no error message, and all the other notebooks (which were giving the same error) are now able to load too.   Thank you.

**Comment by stas00** [comment]
Excellent,
So your jupyter is not respecting the spec then, it should be able to handle:

`   "execution_count": null,`

you still didn't say what your jupyter's version is - jupyter's menu -> Help -> About

**Comment by drscotthawley** [comment]
Jupyter version is 4.4.0, (re)installed today from conda.   I was trying to find out how to print all that other info...thanks. Here it is:

×
About Jupyter Notebook
Server Information:
You are using Jupyter notebook.

The version of the notebook server is: 5.2.2
The server is running on this version of Python:
Python 3.6.5 |Anaconda custom (64-bit)| (default, Aug  3 2018, 14:28:11) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]

Current Kernel Information:
Python 3.6.5 |Anaconda custom (64-bit)| (default, Aug  3 2018, 14:28:11) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.1 -- An enhanced Interactive Python. Type '?' for help.

**Comment by stas00** [comment]
yes, the link you posted in your original post said that it was a bug in jupyter and it has been fixed. so yes, please update to 5.7.0, and it will get resolved.

I will close this ticket, and if you still have an issue please reopen it.

**Comment by stas00** [comment]
we have just updated fastai's dependencies to jupyter-client>=5.2.3

**Comment by stas00** [comment]
> So...how did you get 5.7.0?

sorry, I didn't realize it I got it from the unreleased git. But 5.2.3 will do the trick.

**Comment by drscotthawley** [comment]
Actually, installing client 5.2.3 did *not* fix the issue for me (after checking out a fresh course-v3 repo, the errors returned.)

But what *did* fix the issue for me was to install a new version of `notebook`, either using the `pip` that is part of anaconda`
`pip install notebook==5.7.0`

Or by running `conda install notebook=5.7.0`  (I tried both ways, uninstalling notebook in between).

Either way solves the problem.  Thus upgrading the dependency to notebook>=5.7.0 should have the desired effect.   

×
About Jupyter Notebook
Server Information:
You are using Jupyter notebook.

The version of the notebook server is: 5.7.0
The server is running on this version of Python:
Python 3.6.5 |Anaconda custom (64-bit)| (default, Aug  3 2018, 14:28:11) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]

Current Kernel Information:
Python 3.6.5 |Anaconda custom (64-bit)| (default, Aug  3 2018, 14:28:11) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.1 -- An enhanced Interactive Python. Type '?' for help.



....With that, all the notebooks work fine as the currently are in this repo.  Problem now resolved for me.  Thanks very much @stas00 !

**Comment by stas00** [comment]
Awesome - thank you for helping out on that, @drscotthawley . I got totally lost in all the different jupyter packages. 
notebook>=5.7.0 is the new dependency - so everybody will get it right.

**Comment by NarasimhaM3101** [comment]
Stas00: Your suggestion worked like a charm. No errors so far. Thanks
perl -pi -e 's|execution_count": null|execution_count": 1|g' nbs/dl1/*ipynb
it will change 'null' to a number.
