### ISSUE TITLE
planet notebook - kaggle download

### ISSUE THREAD

**Issue by kasparlund** [fastai/course-v3#91]
The note book should also include the following comments:

To make the kaggle download work you have to :
-go to the kaggle competition and click “Late submission” and confirm by an sms code
-go to the datapage and accept the rule (the dialog box

**Comment by lesscomfortable** [comment]
Hey! The lesson was about using the competition's data to experiment, not to compete in that specific competition so students do not need to submit their results. The steps to accept the rules are described in the notebook.
