### ISSUE TITLE
Official dockerfile for the course

### ISSUE THREAD

**Issue by ThatAIGeek** [fastai/course-v3#97]
Hi!
Is there a need for an official dockerfile for the course? I've already created one on the forum, but maybe it's a good idea to have it in the repo?
Obviously, I'm willing to help with that.

**Comment by Liberus** [comment]
I've created a separate repo for now: https://github.com/Liberus/fastai_part1_docker

**Comment by jph00** [comment]
Thanks a lot for the offer! We'd rather not offer an official dockerfile, but thanks a lot for the offer, and for making yours available on the forum. Feel free to add a link to it on one of the wiki topics there too.
